format = '''
$username$hostname$directory$git_branch $character
'''

[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style)'
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)@[$hostname](bold green) '
disabled = false

[directory]
style = 'cyan bold dimmed'
format='\[[$path]($style)[$read_only]($read_only_style)\] '

[git_branch]
symbol = '🌱 '
truncation_length = 4
truncation_symbol = ''
