format = """
$username\
$hostname\
$directory\
$git_branch\
$character
"""

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style)'
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)@[$hostname](bold green) '
disabled = false

[directory]
style = 'cyan bold dimmed'
format='[$path]($style)[$read_only]($read_only_style) '
truncate_to_repo = false

[git_branch]
format = '\([$symbol$branch(:$remote_branch)]($style)\) '
truncation_length = 4
truncation_symbol = ''
